### ISSUE TITLE
CSRF脆弱性があります

### ISSUE THREAD

**Issue by takumi1001** [ssf2xguile/TsukuReview#5]
セキュスペの勉強をしているのでセキュリティの話を・・・

# `/accounts/delete_complete`
`http://127.0.0.1:8000/accounts/delete_complete`をログイン状態のユーザーに踏ませるとアカウントが削除されてしまいます。

`/accounts/delete_complete`でCSRF検証が行われていないように見えます。重要な操作を検証なしでGETで受けるとろくなことがないです。

考えられる対策:
 - https://www.ipa.go.jp/security/vuln/websecurity-HTML-1_6.html
 - 6-(i)-aが適当な気がします。めんどくさい場合は6-(i)-cでも可能です。

プロフィール変更やパスワード変更は6-(i)-aが実装されているのでCSRFは発生しないと思われます。

# `next=`にも問題があります

例えば、
`http://127.0.0.1:8000/accounts/login/?next=/accounts/delete_complete`のような悪意のあるリンクを作成することができます。
何も知らずに上記のリンクを踏み、ログインをしてしまうとアカウントが削除されます。

考えられる対策:
 - `next=`でリダイレクトできる対象をホワイトリスト方式で検証する。
 - 重要な操作をGETで処理せずPOSTで処理する。

**Comment by ssf2xguile** [comment]
ご報告ありがとうございます。アカウント削除時にCSRF検証を行うように修正しました。

**Comment by takumi1001** [comment]
djangoの機能でいい感じにできるんですね　僕も勉強になりました！
